---
  - name: set hostname
    shell: hostnamectl set-hostname {{ master_hostname }}
  
  - name: vi hosts
    shell: |
      echo "{{ master_hostname_ip }} {{ master_hostname }}" >> /etc/hosts
      echo "{{ node_hostname_ip }} {{ node_hostname }}" >> /etc/hosts

  - name: Stop and disable firewalld.
    systemd:
      name: firewalld
      state: stopped
      enabled: no

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: swap off
    shell: swapoff -a

  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: iptables
    shell: |
      echo 1 > /proc/sys/net/ipv4/ip_forward
      echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
      echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.conf
      modprobe br_netfilter
      echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf
      sysctl -p

  - name: Copy repo file with owner and permissions
    copy:
      src: kubernetes.repo
      dest: /etc/yum.repos.d
      owner: root
      group: root
      mode: '0644'

  - name: join docker-ce repo
    shell: |
      yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      yum clean all
      yum repolist -y
  
  - name: list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - wget
      - net-tools
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: yum install packages
    shell: |
      yum install docker-ce-{{docker_version}} --nogpgcheck -y
      yum install kubelet-{{kubelet_version}}  -y
      yum install kubectl-{{kubectl_version}}  -y
      yum install kubeadm-{{kubeadm_version}}  -y

  - name: yum clean
    shell: yum clean all

  - name: docker service start && enable
    systemd:
      state: started
      enabled: yes
      name: docker

  - name: kubelet service start && enable
    systemd:
      state: started
      enabled: yes
      name: kubelet

  - name: k8s master init
    shell: |
      kubeadm init --apiserver-advertise-address={{ master_hostname_ip }} --pod-network-cidr={{ pod_network_cidr_network }} --service-cidr={{ service_cidr_network }} --kubernetes-version={{ k8s_version }} --cri-socket="/var/run/dockershim.sock"
      mkdir -p $HOME/.kube
      cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      chown $(id -u):$(id -g) $HOME/.kube/config

  - name: install flannel
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  - name: Copy dashboard file with owner and permissions
    copy:
      src: recommended.yaml
      dest: /root
      owner: root
      group: root
      mode: '0644'

  - name: Copy dashboard file with owner and permissions
    copy:
      src: admin-role.yaml
      dest: /root
      owner: root
      group: root
      mode: '0644'
    
  - name: install dashboard
    shell: |
      kubectl apply -f /root/recommended.yaml
      kubectl apply -f /root/admin-role.yaml